apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.dug.neo4j.app_name }}
  name: {{ .Values.dug.neo4j.deployment_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dug.neo4j.app_name }}
  securityContext:
    fsGroup: 1001
  template:
    metadata:
      labels:
        app: {{ .Values.dug.neo4j.app_name }}
    spec:
      containers:
      - image: {{ .Values.dug.neo4j.image }}:{{ .Values.dug.neo4j.image_tag }}
        name: {{ .Values.dug.neo4j.app_name }}-container
        env:
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dug.secrets.name }}
              key: NEO4J_PASSWORD
        - name: NEO4J_HOST
          value: {{ .Values.dug.neo4j.service_name }}
        volumeMounts:
        - mountPath: /bitnami
          name: neo4j
        ports:
          - containerPort: {{ .Values.dug.neo4j.http_port }}
          - containerPort: {{ .Values.dug.neo4j.https_port }}
          - containerPort: {{ .Values.dug.neo4j.bolt_port }}
      volumes:
      - name: neo4j
        persistentVolumeClaim:
          claimName: {{ .Values.dug.neo4j.pvc_name }}
