language: python
services:
  - docker
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - make install
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up -d
script:
  - make test
after_script:
  - docker-compose down
deploy:
  - provider: script
    script: make DOCKER_REPO=harbor.renci.org publish.image