version: '3.0'

#################################################################################
##
## A service stack for the HeLx semantic search framework.
##
## NOTE: .env contains *_HOST variables that are set to internal docker service
##       names. These names resolve to an IP address *within* the docker machine
##       CIDR block, not your local development machine.
##
## NOTE: To connect to a service running in docker machine, from your local
##       development machine, you will need to follow the steps in the Quickstart
##       section of the README.md and set/export the env vars with special attention
##       paid to the env vars: ELASTIC_API_HOST, and REDIS_HOST.
##
#################################################################################
services:

  #################################################################################
  ##
  ## The OpenAPI endpoint for search. This is the only service to be
  ## exposed beyond the internal network.
  ##
  #################################################################################
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
      - redis
      - nboost
    restart: always
    environment:
      ELASTIC_API_HOST: "$ELASTIC_API_HOST"
      ELASTIC_PASSWORD: "$ELASTIC_PASSWORD"
      NBOOST_API_HOST: "$NBOOST_API_HOST"
      REDIS_HOST: "$REDIS_HOST"
      REDIS_PASSWORD: "$REDIS_PASSWORD"
      FLASK_ENV: "development"
      PYTHONUNBUFFERED: "TRUE"
    entrypoint: [ "gunicorn",
                     "--workers=$API_WORKERS", "--name=helx-search",
                     "--bind=0.0.0.0:$API_PORT", "--timeout=$API_TIMEOUT",
                     "--log-level=DEBUG", "--enable-stdio-inheritance", "--reload", "helx.search.api:app" ]
    volumes:
      - ./src:/home/helx/helx
    ports:
      - $API_PORT:$API_PORT

  #################################################################################
  ##
  ## A search engine providing scalable indexing and full text search.
  ##
  #################################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - $DATA_DIR/elastic:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'

  #################################################################################
  ##
  ## A memory cache for results of high volume service requests.
  ##
  #################################################################################
  redis:
    image: 'bitnami/redis:5.0.8'
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - $DATA_DIR/redis:/bitnami/redis/data
    ports:
      - '6379:6379'

  #################################################################################
  ##
  ## A scalable, search-engine-boosting platform for developing models to improve
  ## search results.
  ##
  #################################################################################
  nboost:
    image: koursaros/nboost:0.3.9-pt
    ports:
      - '8000:8000'