version: '3.0'

#################################################################################
##
## A service stack for the Dug semantic search framework.
##
#################################################################################
services:

  #################################################################################
  ##
  ## The OpenAPI endpoint for search. This is the only service to be
  ## exposed beyond the internal network.
  ##
  #################################################################################
  api:
    image: heliumdatastage/dug:latest
    networks:
      - dug-network
    environment:
      - ELASTIC_API_HOST=dug_elasticsearch_1
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    entrypoint: [ "gunicorn",
                     "--workers=$API_WORKERS", "--name=dug",
                     "--bind=0.0.0.0:$API_PORT", "--timeout=$API_TIMEOUT", "dug.api:app" ]
#    entrypoint: [ "python", "-m", "dug.api", "--port", "5551" ]
#    volumes:
#      - $PWD:/home/dug/dug
    ports:
      - $API_PORT:$API_PORT

  #################################################################################
  ##
  ## A search engine providing scalable indexing and full text search.
  ##
  #################################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    networks:
      - dug-network
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - $ELASTIC_DATA:/bitnami/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'

  #################################################################################
  ##
  ## A graph database provides query over linked data to drive indexing.
  ##
  #################################################################################
  neo4j:
    image: bitnami/neo4j:3.5.14
    networks:
      - dug-network
    environment:
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
      - NEO4J_HOST=$HOSTNAME
    volumes:
      - $NEO4J_DATA:/bitnami
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

  #################################################################################
  ##
  ## A memory cache for results of high volume service requests.
  ##
  #################################################################################
  redis:
    image: 'bitnami/redis:5.0.8'
    networks:
      - dug-network
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - $REDIS_DATA:/bitnami/redis/data
    ports:
      - '6379:6379'

  #################################################################################
  ##
  ## The Search frontend for dug
  ##
  #################################################################################
  client:
    image: 'heliumdatastage/dug-search-client:81d7d7d'
    networks:
      - dug-network
    ports:
      - 80:8080


networks:
  dug-network:
    driver: bridge

